import { ArrowRight, LockKeyhole } from 'lucide-react';
import { useState } from 'react';

export function LoginView(props: {
  onLogin: (token: string) => Promise<void>;
  error?: string;
}): React.JSX.Element {
  const [token, setToken] = useState('');
  const [submitting, setSubmitting] = useState(false);

  return (
    <main className="login-page">
      <section className="login-card">
        <div className="brand-mark brand-mark-large" aria-hidden="true">
          F
        </div>
        <p className="eyebrow">Private concierge</p>
        <h1>Sign in to Flow</h1>
        <p className="muted login-copy">
          Use a personal access token generated by the Flow operator. The browser exchanges it for
          an HTTP-only session and does not store the token.
        </p>
        <form
          onSubmit={(event) => {
            event.preventDefault();
            if (token.trim() === '') return;
            setSubmitting(true);
            void props.onLogin(token.trim()).finally(() => setSubmitting(false));
          }}
        >
          <label htmlFor="access-token">Access token</label>
          <div className="token-field">
            <LockKeyhole size={17} aria-hidden="true" />
            <input
              id="access-token"
              type="password"
              autoComplete="off"
              value={token}
              onChange={(event) => setToken(event.target.value)}
              placeholder="flow_pat_…"
              required
            />
          </div>
          {props.error === undefined ? null : <p className="form-error">{props.error}</p>}
          <button className="button button-primary button-full" type="submit" disabled={submitting}>
            {submitting ? 'Signing in…' : 'Continue'}
            <ArrowRight size={17} aria-hidden="true" />
          </button>
        </form>
      </section>
    </main>
  );
}
